---
- name: Ensure dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - python-gpgme
  become: yes

- name: Install dropbox daemon
  command: dropbox start -i
  args:
    creates: "{{ lookup('env', 'HOME') }}/.dropbox/dropbox.pid"
